# A TOML plugin for proto:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "air"
type = "cli"

[platform.linux]
download-file = "air_{version}_linux_{arch}.tar.gz"

[platform.macos]
download-file = "air_{version}_darwin_{arch}.tar.gz"

[platform.windows]
download-file = "air_{version}_windows_{arch}.tar.gz"

[install]
checksum-url = "https://github.com/cosmtrek/air/releases/download/v{version}/air_{version}_checksums.txt"
download-url = "https://github.com/cosmtrek/air/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[resolve]
git-url = "https://github.com/cosmtrek/air"
