# A TOML plugin for proto:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "wiretap"
type = "cli"

[platform.linux]
download-file = "wiretap_{version}_linux_{arch}.tar.gz"

[platform.macos]
download-file = "wiretap_{version}_darwin_{arch}.tar.gz"

[platform.windows]
download-file = "wiretap_{version}_windows_{arch}.tar.gz"

[install]
checksum-url = "https://github.com/pb33f/wiretap/releases/download/v{version}/checksums.txt"
download-url = "https://github.com/pb33f/wiretap/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[resolve]
git-url = "https://github.com/pb33f/wiretap"
